[build]
  publish = "public/original"
  command = '''hugo -s exampleSite --config "exampleSite/config.toml" \
&& hugo -s exampleSite --config "exampleSite/config.toml,exampleSite/config-original.toml"'''

[build.environment]
  HUGO_VERSION = "0.51"
  HUGO_THEME = "hugo-theme-docdock"
  HUGO_THEMESDIR = "/opt/build"

# [context.production.environment]
#   HUGO_VERSION = "0.51"

# [context.deploy-preview.environment]
#   HUGO_VERSION = "0.51"

# [context.branch-deploy.environment]
#   HUGO_VERSION = "0.51"
  
